import Head from "next/head";
import { Navbar } from "../../ui/Navbar";
import { Hero } from "./Hero";
import { SpotSearch } from "./SpotSearch";
import { MobileAd } from "./MobileAd";
import { CallToAction } from "./CallToAction";
import { Footer } from "../../ui/Footer";

export const HomePage = () => {
  return (
    <div className="page-container">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <SpotSearch />
      <MobileAd />
      <CallToAction />
      <Footer />
    </div>
  );
};
