import { NextPage } from "next";
import Head from "next/head";
import { makeStyles } from "@material-ui/styles";
import { Grid, Theme, Typography } from "@material-ui/core";
import { GoogleLoginBtn } from "./GoogleLoginBtn";
import { AppleLoginBtn } from "./AppleLoginBtn";
import { Logo } from "../../ui/Logo";

const useStyles = makeStyles((theme: Theme) => ({
  pageContainer: {
    overflow: "hidden !important",
    height: "100vh",
  },
  logoWrap: {
    position: "absolute",
    top: "20px",
    left: "2.5vw",
    zIndex: 99999,
  },
  slantWrap: {
    position: "relative",
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  bgSlant: {
    maxHeight: "100vh",
  },
  welcomeText: {
    color: theme.palette.primary.main,
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    left: "3vw",
    maxWidth: "80%",
  },
  loginContainer: {
    marginTop: "12%",
    marginLeft: "7%",
    [theme.breakpoints.down("lg")]: {
      marginTop: "0",
      marginLeft: "0",
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%,-50%)",
    },
  },
  mobileBgSlantWrap: {
    position: "absolute",
    width: "auto",
    height: "auto",
    [theme.breakpoints.up("lg")]: {
      display: "none",
    },
  },
  mobileBgSlantImg: {
    width: "55vw",
    display: "block",
  },
}));

export const LoginPage: NextPage = () => {
  const classes = useStyles();
  return (
    <div className={`page-container ${classes.pageContainer}`}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.logoWrap}>
        <Logo />
      </div>
      <Grid container direction="row">
        <Grid item>
          <div
            className={classes.mobileBgSlantWrap}
            style={{ top: 0, left: 0 }}
          >
            <img
              className={classes.mobileBgSlantImg}
              src="/svgs/login_slant_3/bg_slant_3_test.svg"
              alt=""
            />
          </div>
          <div
            className={classes.mobileBgSlantWrap}
            style={{ bottom: "0px", right: 0 }}
          >
            <img
              className={classes.mobileBgSlantImg}
              src="/svgs/login_slant_3/bg_slant_3_test_1.svg"
              alt=""
            />
          </div>
          <div className={classes.slantWrap}>
            <Typography
              className={classes.welcomeText}
              variant="h3"
              component="h3"
            >
              Welcome back
            </Typography>
            <img
              className={classes.bgSlant}
              src="/svgs/login_slant_3/bg_slant_3_black.svg"
              alt=""
            />
          </div>
        </Grid>
        <Grid className={classes.loginContainer} item>
          <Typography
            variant="h3"
            component="h3"
            style={{ marginBottom: "30px" }}
          >
            Login
          </Typography>
          <Grid container direction="column" spacing={4}>
            <Grid item>
              <GoogleLoginBtn />
            </Grid>
            <Grid item>
              <AppleLoginBtn />
            </Grid>
          </Grid>
        </Grid>
      </Grid>
    </div>
  );
};
