import Head from "next/head";
import { Navbar } from "../shared-components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>ParKit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </>
  );
}
